########################################
# USER VARIABLES
PACKNAME = tablesorter.opx
SRC = tablesorter.opa
PLUGIN = tablesorter.opp
PLUGINDIR = ./
OPAOPT = --parser js-like

all: pack

include Makefile.common
