########################################
# USER VARIABLES
PACKNAME = html2text.opx
SRC = html2text.opa
PLUGIN = html2text.opp
PLUGINDIR = ./
OPAOPT = --parser js-like

all: pack

include Makefile.common
