########################################
# USER VARIABLES
PACKNAME = bootstrap.treeview.opx
SRC = bootstrap.treeview.opa
PLUGIN = treeview.opp
PLUGINDIR = ./
OPAOPT = --parser js-like

all: pack

include Makefile.common
