########################################
# USER VARIABLES
PACKNAME = resumable.opx
SRC = resumable.opa
PLUGIN = resumable.opp
PLUGINDIR = ./
OPAOPT = --parser js-like

all: pack

include Makefile.common
