########################################
# USER VARIABLES
PACKNAME = select2.opx
SRC = select2.opa
MAINSRC = example.opa
PLUGIN = select2.opp
PLUGINDIR = ./
OPAOPT = --parser js-like
EXE = example.exe

all: pack

example: exe

include Makefile.common
