########################################
# USER VARIABLES
PACKNAME = mailparser.opx
SRC = mailparser.opa
PLUGIN = mailparser.opp
PLUGINDIR = ./
OPAOPT = --parser js-like

all: pack

include Makefile.common
