########################################
# USER VARIABLES
PACKNAME = tweetnacl.server.opx
SRC = tweetnacl.server.opa
PLUGIN = servernacl.opp
PLUGINDIR = ./
OPAOPT = --parser js-like

all: pack

include Makefile.common
